# This file was generated by GoReleaser. DO NOT EDIT.
cask "eraser" do
  version "0.8.1"

  on_macos do
    on_arm do
      sha256 "9d045762cede10961d828358562c4d76381bb263f556f05373485f997b07e5c4"
      url "https://github.com/drumandbytes/eraser/releases/download/v#{version}/eraser_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "61985bdb3afda9dbfb04f19aec869b8613706d0630185d2b70aaa8de7f5a1d6f"
      url "https://github.com/drumandbytes/eraser/releases/download/v#{version}/eraser_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "5227011cd0da9a389e4fee8e1816ba35483fd72d9d93b2fb6fe8153397193c56"
      url "https://github.com/drumandbytes/eraser/releases/download/v#{version}/eraser_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "59c013e04338f13001448598f57711c400abcbb416dce852779e55cb1a741bcb"
      url "https://github.com/drumandbytes/eraser/releases/download/v#{version}/eraser_#{version}_linux_amd64.tar.gz"
    end
  end

  name "eraser"
  desc "Send data removal requests to data brokers"
  homepage "https://eraser.drumandbytes.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "eraser"

  # No zap stanza required

  caveats <<~EOS
    Config lives at ~/.eraser/config.yaml. Start with:
      eraser serve      # web UI at http://localhost:8080
    `eraser fill` / `eraser confirm` also need Chrome installed.
  EOS
end
