# This file was generated by GoReleaser. DO NOT EDIT.
cask "eraser" do
  version "0.7.4"

  on_macos do
    on_arm do
      sha256 "162dde52ca9c588cf0ea74b9257b1c5fc8f6013ad9b60e09635d471bcebd749a"
      url "https://github.com/drumandbytes/eraser/releases/download/v#{version}/eraser_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c51a8e1192f9aacbb3e5c86b8113b47cec236900ba965b2de06070e825697432"
      url "https://github.com/drumandbytes/eraser/releases/download/v#{version}/eraser_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "11669cac8bbd8623972ddb4e59a8ffd3dbf1668e241147362600633b94d1e126"
      url "https://github.com/drumandbytes/eraser/releases/download/v#{version}/eraser_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "75020a450a0b28da09c6bac45b8ecdadb8fade7b5311458e8d548504da8ccc9e"
      url "https://github.com/drumandbytes/eraser/releases/download/v#{version}/eraser_#{version}_linux_amd64.tar.gz"
    end
  end

  name "eraser"
  desc "Send data removal requests to data brokers"
  homepage "https://eraser.drumandbytes.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "eraser"

  # No zap stanza required

  caveats <<~EOS
    Config lives at ~/.eraser/config.yaml. Start with:
      eraser serve      # web UI at http://localhost:8080
    `eraser fill` / `eraser confirm` also need Chrome installed.
  EOS
end
