# This file was generated by GoReleaser. DO NOT EDIT.
cask "eraser" do
  version "0.9.1"

  on_macos do
    on_arm do
      sha256 "50c247361d51b6390c581d29e69249bb33a15f7a5e1ee1c8f44026f336553532"
      url "https://github.com/drumandbytes/eraser/releases/download/v#{version}/eraser_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "1c45ad79a2d933fce2f474b3dd5a683c5e3f3f8ccfbfe49ad70db4e24dae3ce8"
      url "https://github.com/drumandbytes/eraser/releases/download/v#{version}/eraser_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "9ec17b668202b2e9fabe7c1a09762c5217c41992f57488841ba7631d9e0ed450"
      url "https://github.com/drumandbytes/eraser/releases/download/v#{version}/eraser_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d52d09543b29f1516be72e996c4779857573a43c0914bd1ebe28f854cfc303ee"
      url "https://github.com/drumandbytes/eraser/releases/download/v#{version}/eraser_#{version}_linux_amd64.tar.gz"
    end
  end

  name "eraser"
  desc "Send data removal requests to data brokers"
  homepage "https://eraser.drumandbytes.dev/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "eraser"

  # No zap stanza required

  caveats <<~EOS
    Config lives at ~/.eraser/config.yaml. Start with:
      eraser serve      # web UI at http://localhost:8080
    `eraser fill` / `eraser confirm` also need Chrome installed.
  EOS
end
